apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: momomats
resources:
  - momomats.yaml
  - momomats-httproute.yaml
  - momomats-target-group.yaml
images:
  - name: momomats-image
    newName: ghcr.io/shadowg9/momomats
    newTag: 6c686eabc00e0b31ab9d2b78ff8bd4923ceec8ac
