apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: momomats
resources:
  - momomats.yaml
  - momomats-httproute.yaml
  - momomats-target-group.yaml
images:
  - name: momomats-image
    newName: ghcr.io/shadowg9/momomats
    newTag: df4a73fb5afbf2c4211739112c34c0e3627e7517
