apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: momomats
resources:
  - momomats.yaml
  - momomats-httproute.yaml
  - momomats-target-group.yaml
images:
  - name: momomats-image
    newName: ghcr.io/shadowg9/momomats
    newTag: fecafef4f29a57eb37e44fc88843639a669635f0
