apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: momomats-tg-config
  namespace: momomats
spec:
  targetReference:
    name: momomats-service
  defaultConfiguration:
    targetType: ip