apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: image-updater-config
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/shadowg9/MomoMats.git
    targetRevision: main
    path: argocd/image-updater-config

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false